//! The table codec: one static `buffa::table::Table` per message and a
//! `Message` impl that forwards to the interpreters in `buffa::table`.
//!
//! Which messages get one is decided by [`crate::table_plan`]; this module
//! emits the code for a message the plan selected.

use proc_macro2::TokenStream;
use quote::{format_ident, quote};

use crate::context::MessageScope;
use crate::generated::descriptor::field_descriptor_proto::Type;
use crate::generated::descriptor::DescriptorProto;
use crate::idents::rust_path_to_tokens;
use crate::message::classify_field;
use crate::table_plan::{table_fields, Card, TableField};
use crate::CodeGenError;

/// The name of the static table of the message struct `rust_name`.
fn table_ident(rust_name: &str) -> proc_macro2::Ident {
    format_ident!("__BUFFA_TABLE_{}", rust_name)
}

/// The path of the static table of the message type whose struct is at
/// `type_path`: the last segment is replaced by the table's name.
fn table_path(type_path: &str) -> Result<TokenStream, CodeGenError> {
    if type_path.starts_with("::") || type_path.starts_with("crate::") {
        return Err(CodeGenError::Other(format!(
            "table codec: message type `{type_path}` is generated by another crate, \
             so it has no table here"
        )));
    }
    let (head, last) = match type_path.rsplit_once("::") {
        Some((head, last)) => (format!("{head}::"), last),
        None => (String::new(), type_path),
    };
    Ok(rust_path_to_tokens(&format!("{head}__BUFFA_TABLE_{last}")))
}

/// The table ABI this generator emits, which `buffa::table::ABI` must equal
/// for the generated tables to build. Bump both when the meaning of an existing
/// table entry changes.
pub(crate) const TABLE_ABI: u32 = 1;

/// The static table and `impl Message` of a message the plan selected.
///
/// # Errors
///
/// Returns an error if the message cannot use the table, which the plan
/// should have ruled out.
pub(crate) fn generate_table_impl(
    scope: MessageScope<'_>,
    msg: &DescriptorProto,
    rust_name: &str,
    resolver: &crate::imports::ImportResolver,
) -> Result<TokenStream, CodeGenError> {
    let MessageScope {
        ctx,
        proto_fqn,
        features,
        ..
    } = scope;
    let name = format_ident!("{}", rust_name);
    let table = table_ident(rust_name);
    let dotted_fqn = format!(".{proto_fqn}");

    let fields = table_fields(ctx, msg, &dotted_fqn, features).map_err(|why| {
        CodeGenError::Other(format!(
            "table codec: {dotted_fqn} cannot use the table: {}",
            why.detail
        ))
    })?;

    let mut entries: Vec<TokenStream> = Vec::with_capacity(fields.len());
    let mut aux: Vec<TokenStream> = Vec::new();
    for f in &fields {
        let (entry, aux_item) = field_entry(scope, msg, &name, f, aux.len(), resolver)?;
        entries.push(entry);
        aux.extend(aux_item);
    }

    let dense = dense_lookup(&fields);
    let abi = proc_macro2::Literal::u32_unsuffixed(TABLE_ABI);

    let unknown = if ctx.preserve_unknown_fields(proto_fqn) {
        quote! { __buffa_unknown_fields }
    } else {
        quote! { none }
    };

    Ok(quote! {
        #[doc(hidden)]
        #[allow(non_upper_case_globals)]
        pub(crate) static #table: ::buffa::table::Table<#name> = ::buffa::__table!(
            #name,
            abi = #abi,
            entries = [#(#entries),*],
            dense = &[#(#dense),*],
            aux = [#(#aux),*],
            unknown = #unknown,
        );

        impl ::buffa::Message for #name {
            fn compute_size(&self, cache: &mut ::buffa::SizeCache) -> u32 {
                #table.compute_size(self, cache)
            }

            fn write_to(&self, cache: &mut ::buffa::SizeCache, buf: &mut impl ::buffa::EncodeSink) {
                #table.write_to(self, cache, buf);
            }

            fn merge_field(
                &mut self,
                tag: ::buffa::encoding::Tag,
                buf: &mut impl ::buffa::bytes::Buf,
                ctx: ::buffa::DecodeContext<'_>,
            ) -> ::core::result::Result<(), ::buffa::DecodeError> {
                #table.merge_field(self, tag, buf, ctx)
            }

            fn merge_to_limit(
                &mut self,
                buf: &mut impl ::buffa::bytes::Buf,
                ctx: ::buffa::DecodeContext<'_>,
                limit: usize,
            ) -> ::core::result::Result<(), ::buffa::DecodeError> {
                #table.merge_to_limit(self, buf, ctx, limit)
            }

            fn merge_length_delimited(
                &mut self,
                buf: &mut impl ::buffa::bytes::Buf,
                ctx: ::buffa::DecodeContext<'_>,
            ) -> ::core::result::Result<(), ::buffa::DecodeError> {
                #table.merge_length_delimited(self, buf, ctx)
            }

            fn clear(&mut self) {
                *self = ::core::default::Default::default();
            }
        }
    })
}

/// `dense[n]` is one plus the index of the field numbered `n`, or `0`, for
/// the numbers up to the highest field number below 64. Empty, so that the
/// table searches instead, for a message with 255 fields or more, because
/// `Table::new` accepts a dense array only when every index fits below 255.
fn dense_lookup(fields: &[TableField<'_>]) -> Vec<u8> {
    if fields.len() >= 255 {
        return Vec::new();
    }
    let top = fields
        .iter()
        .map(|f| f.number)
        .filter(|&n| n < 64)
        .max()
        .unwrap_or(0) as usize;
    let mut dense = vec![0u8; top + 1];
    for (i, f) in fields.iter().enumerate() {
        if let Some(slot) = dense.get_mut(f.number as usize) {
            // At most 254 fields, so this fits.
            *slot = (i + 1) as u8;
        }
    }
    dense
}

/// The `__table_entry!` for one field, and the aux descriptor it needs, which
/// goes at index `aux_index` of the table's aux array.
fn field_entry(
    scope: MessageScope<'_>,
    msg: &DescriptorProto,
    name: &proc_macro2::Ident,
    f: &TableField<'_>,
    aux_index: usize,
    resolver: &crate::imports::ImportResolver,
) -> Result<(TokenStream, Option<TokenStream>), CodeGenError> {
    let MessageScope {
        ctx,
        current_package,
        nesting,
        ..
    } = scope;
    let field = f.field;
    let field_name = field.name.as_deref().unwrap_or("");
    let ident = ctx.field_ident(field_name, field.number.unwrap_or(0));
    let kind = format_ident!("{}", f.kind);
    let number = f.number;

    let aux_u16 = || {
        u16::try_from(aux_index).map_err(|_| {
            CodeGenError::Other(format!(
                "table codec: {}.{field_name}: a message has more than 65535 fields \
                 that need a descriptor",
                scope.proto_fqn
            ))
        })
    };
    let type_path = |what: &str| -> Result<String, CodeGenError> {
        let type_name = field
            .type_name
            .as_deref()
            .ok_or(CodeGenError::MissingField("field.type_name"))?;
        ctx.rust_type_relative(type_name, current_package, nesting)
            .ok_or_else(|| CodeGenError::Other(format!("{what} type '{type_name}' not found")))
    };

    // The table is not among the imports that `idiomatic_imports` shortens
    // paths with, so its path is built from the unshortened one.
    let unshortened_path = || -> Result<String, CodeGenError> {
        let type_name = field
            .type_name
            .as_deref()
            .ok_or(CodeGenError::MissingField("field.type_name"))?;
        let split = ctx
            .rust_type_relative_split(type_name, current_package, nesting)
            .ok_or_else(|| CodeGenError::Other(format!("message type '{type_name}' not found")))?;
        Ok(if split.to_package.is_empty() {
            split.within_package
        } else {
            format!("{}::{}", split.to_package, split.within_package)
        })
    };

    match f.ty {
        Type::TYPE_MESSAGE => {
            let child = type_path("message")?;
            let child_ty = rust_path_to_tokens(&child);
            let type_name = field
                .type_name
                .as_deref()
                .ok_or(CodeGenError::MissingField("field.type_name"))?;
            // A child with a table is reached through it, and any other, an
            // unrolled message, a message of another crate or a well-known
            // type, through its `Message` impl.
            let child_table = if ctx.uses_table_codec(type_name) {
                Some(table_path(&unshortened_path()?)?)
            } else {
                None
            };
            let (slot, aux_item) = if f.card == Card::Repeated {
                let vt = match &child_table {
                    Some(table) => quote! { ::buffa::table::RepVt::new::<#child_ty>(&#table) },
                    None => quote! { ::buffa::table::RepVt::new_via_message::<#child_ty>() },
                };
                (
                    quote! { ::buffa::alloc::vec::Vec<#child_ty> },
                    quote! { ::buffa::table::Aux::Rep(&#vt) },
                )
            } else {
                let slot = classify_field(scope, msg, field, resolver)?.rust_type;
                let vt = match &child_table {
                    Some(table) => quote! { ::buffa::table::MsgVt::new::<#slot>(&#table) },
                    None => quote! { ::buffa::table::MsgVt::new_via_message::<#slot>() },
                };
                (slot, quote! { ::buffa::table::Aux::Msg(&#vt) })
            };
            let aux = aux_u16()?;
            Ok((
                quote! {
                    ::buffa::__table_entry!(#name, #ident, #kind, #number, aux = #aux, slot = #slot)
                },
                Some(aux_item),
            ))
        }
        Type::TYPE_ENUM => {
            let enum_ty = rust_path_to_tokens(&type_path("enum")?);
            let repeated = matches!(f.card, Card::Repeated | Card::Packed);
            let shape = match (repeated, f.card == Card::Optional, f.closed_enum) {
                (true, _, true) => quote! { RepeatedClosed },
                (true, _, false) => quote! { RepeatedOpen },
                (false, true, true) => quote! { OptionalClosed },
                (false, true, false) => quote! { OptionalOpen },
                (false, false, true) => quote! { ImplicitClosed },
                (false, false, false) => quote! { ImplicitOpen },
            };
            let shape = quote! { ::buffa::table::#shape<#enum_ty> };
            let aux = aux_u16()?;
            Ok((
                quote! {
                    ::buffa::__table_entry!(
                        #name, #ident, #kind, #number,
                        aux = #aux,
                        slot = <#shape as ::buffa::table::EnumShape>::Slot
                    )
                },
                Some(quote! {
                    ::buffa::table::Aux::Enum(&::buffa::table::EnumVt::new::<#shape>())
                }),
            ))
        }
        _ => Ok((
            quote! { ::buffa::__table_entry!(#name, #ident, #kind, #number) },
            None,
        )),
    }
}
